da <- read.csv("Data/FI1.csv", stringsAsFactors = FALSE)
da$Outcome <- factor(da$Outcome)
str(da)
par(mfrow = c(1,2))
daclear <- subset(da, da$Clear == 1)
boxplot(da$Mark)
boxplot(daclear$Mark)
max(da$Mark, na.rm = TRUE)
max(daclear$Mark, na.rm = TRUE)
min(da$Mark, na.rm = TRUE)
min(daclear$Mark, na.rm = TRUE)
length(daclear$Mark)
length(da$Mark)